version: "3.8"

name: private-isu
services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/public
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - my_network

  app:
    # Go実装の場合は golang/ PHP実装の場合は php/
    build: golang/
    environment:
      ISUCONP_DB_HOST: mysql
      ISUCONP_DB_PORT: 3306
      ISUCONP_DB_USER: root
      ISUCONP_DB_PASSWORD: root
      ISUCONP_DB_NAME: isuconp
      ISUCONP_MEMCACHED_ADDRESS: memcached:11211
    networks:
      - my_network
    volumes:
      - ./public:/home/public
    init: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g

  mysql:
    image: bitnami/mysql:ssl-certs
    environment:
      #- "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql:/var/lib/mysql
      - ./etc/mysql/conf.d/my.cnf:/etc/my.cnf
      - ./sql:/docker-entrypoint-initdb.d
      - ./logs/mysql:/var/log/mysql
      - ./scripts:/usr/src/scripts
    ports:
      - "3306:3306"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1g
    build:
      context: ./etc/mysql/docker/
      dockerfile: Dockerfile
  memcached:
    image: memcached:1.6
    networks:
      - my_network

volumes:
  mysql:

networks:
  my_network:
